package com.example.tmdbapp.model

data class MovieDetails ( // class needs to be gotten by tmdb api call and generated by moshi
        val id : String ,
        val movieGenre : String,
        val homePageURL : String,
        val imdbID : String
        )